### ISSUE TITLE
URGENT: Complete the "Musical Hospice" page

### ISSUE THREAD

**Issue by prsuyal** [Musical-Memories/musical-memories#11]
HIGH PRIORITY

Add information about the hospice project and our previous successes with it. Embed videos and pictures.

**DEADLINE:** December 17, 2023 11:59 PM

**Comment by AbhinavK05** [comment]
- Add description of hospice project + refugee project (if it happens)
- Add a link to a YouTube playlist of past events
- Embed sign-up form
